### ISSUE TITLE
New header image for 2021

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#21]
The 2020 header image will make a good visual marker to differentiate the 2020 and 2021 sites. Can we get a new image with a similar color scheme, either one that incorporates the bridge logo, or one with a different abstract pattern?

**Comment by kenirwin** [comment]
Last year we used an autogenerated one from: 
https://www.svgbackgrounds.com/

**Comment by dwgreen1** [comment]
Here are the first three options we have:

**Cornered Stairs #1**
<img width="1428" alt="cornered-stairs-1" src="https://user-images.githubusercontent.com/2590810/123146250-ad3bed00-d42b-11eb-9cf9-f35a192a5cf5.png">

**Cornered Stairs #2** 
<img width="1428" alt="cornered-stairs-2" src="https://user-images.githubusercontent.com/2590810/123146305-b75deb80-d42b-11eb-906b-ac53e7da78f6.png">

**Protruding Squares #3**
<img width="1428" alt="protruding-squares" src="https://user-images.githubusercontent.com/2590810/123146341-c0e75380-d42b-11eb-91e0-93278090eb60.png">

Now that I can see these examples, I am not a fan of the first option only because it's too similar to the 2020 website. We should choose something that looks distinctly different from last year's. What are everyone else's thoughts? Do we have any votes for options two or three? Or should we continue to think about it?

**Comment by dwgreen1** [comment]
Here are two more Cornered Stairs options:

**Cornered Stairs #4**
<img width="1391" alt="Screenshot 2021-06-29 at 08 53 47" src="https://user-images.githubusercontent.com/2590810/123801003-da6b1e00-d8b7-11eb-8029-9d8b5615af85.png">

**Cornered Stairs #5**
<img width="1391" alt="Screenshot 2021-06-29 at 08 55 23" src="https://user-images.githubusercontent.com/2590810/123801042-e2c35900-d8b7-11eb-85db-5ec933dd3232.png">

**Comment by hillmk1** [comment]
sure!
