### ISSUE TITLE
Is there an option to open the youtube vid in a new window?

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#7]

**Comment by dwgreen1** [comment]
@kenirwin do you happen to know if there was a reason we added the following query parameter here?

https://github.com/alaoweb/2021.alaoweb.org/blob/4a124f8af4d3092d28b4544ce97e2af5c8bcf56b/_includes/sessions-modals.html#L34

I don't think it was in the original zeppelin repo. I'm guessing it's because it provided the cleanest video layout, but if we remove it, we do get the option back on videos to open them directly in YouTube, as seen in this example from last year's website:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2590810/123970103-d6f29800-d986-11eb-83a4-3f4d67792197.png">

This might be the most straightforward solution for this one. What do you think?
